//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_muzikEntities : DbContext
    {
        public db_muzikEntities()
            : base("name=db_muzikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblAlbum> tblAlbums { get; set; }
        public DbSet<tblAlbumdekiSanatcilar> tblAlbumdekiSanatcilars { get; set; }
        public DbSet<tblAlbumdekiSarkilar> tblAlbumdekiSarkilars { get; set; }
        public DbSet<tblCalmaListelerindekiSarkilar> tblCalmaListelerindekiSarkilars { get; set; }
        public DbSet<tblKullanici> tblKullanicis { get; set; }
        public DbSet<tblKullaniciCalmaListesi> tblKullaniciCalmaListesis { get; set; }
        public DbSet<tblKullaniciRole> tblKullaniciRoles { get; set; }
        public DbSet<tblPremiumKullaniciOdendiBilgi> tblPremiumKullaniciOdendiBilgis { get; set; }
        public DbSet<tblSanatci> tblSanatcis { get; set; }
        public DbSet<tblSanatcininSarkilari> tblSanatcininSarkilaris { get; set; }
        public DbSet<tblSarki> tblSarkis { get; set; }
        public DbSet<tblSarkiTur> tblSarkiTurs { get; set; }
        public DbSet<tblTakipListesi> tblTakipListesis { get; set; }
        public DbSet<tblUlke> tblUlkes { get; set; }
    }
}
