//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalmaListelerindekiSarkilar
    {
        public int ID { get; set; }
        public int SarkiID { get; set; }
        public int KullaniciCalmaListesiID { get; set; }
    
        public virtual tblKullaniciCalmaListesi tblKullaniciCalmaListesi { get; set; }
        public virtual tblSanatcininSarkilari tblSanatcininSarkilari { get; set; }
    }
}
