//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        public tblKullanici()
        {
            this.tblPremiumKullaniciOdendiBilgis = new HashSet<tblPremiumKullaniciOdendiBilgi>();
            this.tblTakipListesis = new HashSet<tblTakipListesi>();
            this.tblTakipListesis1 = new HashSet<tblTakipListesi>();
            this.tblKullaniciCalmaListesis = new HashSet<tblKullaniciCalmaListesi>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
        public short AbonelikTur { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> UlkeID { get; set; }
    
        public virtual tblKullaniciRole tblKullaniciRole { get; set; }
        public virtual tblUlke tblUlke { get; set; }
        public virtual ICollection<tblPremiumKullaniciOdendiBilgi> tblPremiumKullaniciOdendiBilgis { get; set; }
        public virtual ICollection<tblTakipListesi> tblTakipListesis { get; set; }
        public virtual ICollection<tblTakipListesi> tblTakipListesis1 { get; set; }
        public virtual ICollection<tblKullaniciCalmaListesi> tblKullaniciCalmaListesis { get; set; }
    }
}
