//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullaniciRole
    {
        public tblKullaniciRole()
        {
            this.tblKullanicis = new HashSet<tblKullanici>();
        }
    
        public int ID { get; set; }
        public string RolIsmi { get; set; }
    
        public virtual ICollection<tblKullanici> tblKullanicis { get; set; }
    }
}
