//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanatcininSarkilari
    {
        public tblSanatcininSarkilari()
        {
            this.tblCalmaListelerindekiSarkilars = new HashSet<tblCalmaListelerindekiSarkilar>();
        }
    
        public int ID { get; set; }
        public int SarkiID { get; set; }
        public int SanatciID { get; set; }
        public int AlbumID { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan SarkiSure { get; set; }
        public Nullable<int> DinlenmeSayisi { get; set; }
    
        public virtual tblAlbum tblAlbum { get; set; }
        public virtual ICollection<tblCalmaListelerindekiSarkilar> tblCalmaListelerindekiSarkilars { get; set; }
        public virtual tblSanatci tblSanatci { get; set; }
        public virtual tblSarki tblSarki { get; set; }
    }
}
