//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSarkiTur
    {
        public tblSarkiTur()
        {
            this.tblAlbums = new HashSet<tblAlbum>();
            this.tblKullaniciCalmaListesis = new HashSet<tblKullaniciCalmaListesi>();
            this.tblSarkis = new HashSet<tblSarki>();
        }
    
        public int ID { get; set; }
        public string Tur { get; set; }
    
        public virtual ICollection<tblAlbum> tblAlbums { get; set; }
        public virtual ICollection<tblKullaniciCalmaListesi> tblKullaniciCalmaListesis { get; set; }
        public virtual ICollection<tblSarki> tblSarkis { get; set; }
    }
}
