//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muzikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSarki
    {
        public tblSarki()
        {
            this.tblSanatcininSarkilaris = new HashSet<tblSanatcininSarkilari>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> Tur { get; set; }
    
        public virtual ICollection<tblSanatcininSarkilari> tblSanatcininSarkilaris { get; set; }
        public virtual tblSarkiTur tblSarkiTur { get; set; }
    }
}
